name: Dynamic Matrix

on:
  workflow_dispatch:

jobs:
  do-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - docker1
          - docker2
          - docker3
          - docker4
          - docker5
          - docker6
          - docker7
          - docker8
          - docker9
          - docker10

    outputs:
      the-matrix: ${{ fromJson(steps.test.outputs.the-matrix) }}

    steps:
      - name: View the whole matrix as a json string
        run: |
          MATRIX=$(echo '${{ toJson(matrix) }}' | tr -d '\n' | jq '. + {"tag": "1.4892"}')
          MATRIX=$(echo "$MATRIX" | sed "s/\"/'/g")
          echo "$MATRIX"
          echo "the-matrix=$MATRIX" >> $GITHUB_OUTPUT
        id: test

  check-matrix:
    needs: do-build
    runs-on: ubuntu-latest
    steps:
      - name: Check the matrix
        run: |
          echo "The matrix is ${{ needs.do-build.outputs.the-matrix }}"
      
