name: Dynamic Matrix

on:
  workflow_dispatch:

jobs:
  do-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
          - docker1
          - docker2
          - docker3
          - docker4
          - docker5
          - docker6
          - docker7
          - docker8
          - docker9
          - docker10

    outputs:
      the-matrix: ${{ steps.test.outputs.the-matrix }}

    steps:
      - name: View the whole matrix as a json string
        run: |
          echo '${{ toJson(matrix) }}' | jq '. + {"tag": "1.4892"}'
        id: test

      
