# It is no longer correct to use ::set-output name= to set the output variable
# the new syntax is echo "the-matrix=$MATRIX" >> $GITHUB_OUTPUT
# do not use ::set-output anymore

name: Build Docker image and deploy to cluster

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      imageTag: ${{ steps.createTag.outputs.imageTag }}

    steps:
      - name: Create a tag from ${{ inputs.imageName }} and a version number
        id: createTag
        run: |
          echo "imageTag=${{ inputs.imageName }}-1.0" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ${{ needs.build.outputs.imageTag }} to Kubernetes
        run: |
          echo "Deploying ${{ needs.build.outputs.imageTag }} to Kubernetes"
